package world;

public enum TileType {
    Vazio((char) 0),
    Knight((char) 1),
    Wizard((char) 2),
    Healer((char) 3),
    Zombie((char) 4),
    Slime((char) 5),
    Spider((char) 6),
    Sword((char) 7),
    Orc((char) 8),
    Cyclop((char) 9),
    Reaper((char) 10),
    Squid((char) 11),
    MiniDemon((char) 12),
    Goblin((char) 13),
    NoteMusic((char) 14),
    Sphere((char) 15),
    Archer((char) 16),
    Rogue((char) 17),
    Assasin((char) 18),
    Cat((char) 19),
    Bat((char) 20),
    SkeletonShield((char) 21),
    AngryGoblin((char) 22),
    Ghost((char) 23),
    RogueSkeleton((char) 24),
    ScarySkeleton((char) 25),
    DaggerEye((char) 26),
    Napstablook((char) 27),
    FighterSkeleton((char) 28),
    EvilWizard((char) 29),
    UpTriangle((char) 30),
    DownTriangle((char) 31),
    PentagramVar1((char) 32),
    PentagramVar2((char) 33),
    WaterVar1((char) 38),
    WaterVar2((char) 39),
    WaterVar3((char) 40),
    WaterVar4((char) 41),
    WaterVar5((char) 42),
    FloorVar1((char) 46),
    FloorVar2((char) 47),
    PentagramVar3((char) 48),
    PentagramVar4((char) 49),
    FleshFloorVar1((char) 50),
    FleshFloorVar2((char) 51),
    MossVar1((char) 52),
    MossVar2((char) 53),
    FloorTileVar1((char) 61),
    FloorTileVar2((char) 62),
    FloorRockTile((char) 63),
    DryRockyFloorVar1((char) 76),
    DryRockyFloorVar2((char) 77),
    DryRockyFloorVar3((char) 78),
    DryRockyFloorVar4((char) 79),
    DryRockyFloorVar5((char) 92),
    DryRockyFloorVar6((char) 93),
    DryRockyFloorVar7((char) 94),
    DryRockyFloorVar8((char) 95),
    SpiderWebVar1((char) 112),
    SpiderWebVar2((char) 113),
    SpiderWebVar3((char) 114),
    SpiderWebVar4((char) 115),
    Lamp((char) 118),
    DirtRoadVar1((char) 119),
    DirtRoadVar2((char) 120),
    DirtRoadVar3((char) 121),
    DirtRoadVar4((char) 122),
    BonesInFloorVar1((char) 123),
    MushroomVar1((char) 124),
    RoyalVictory((char) 128),
    DirtRoadVar5((char) 131),
    DirtRoadVar6((char) 132),
    DirtRoadVar7((char) 133),
    DirtRoadVar8((char) 134),
    DirtRoadVar9((char) 135),
    DirtRoadVar10((char) 136),
    DirtRoadVar11((char) 137),
    SpiderWebVar5((char) 139),
    MushroomVar2((char) 140),
    RockyFloorVar1((char) 150),
    RockyFloorVar2((char) 151),
    RockyFloorVar3((char) 152),
    RockyFloorVar4((char) 153),
    RockyFloorVar5((char) 154),
    RockyFloorVar6((char) 155),
    Mushroom((char) 156),
    BoneDustVar1((char) 164),
    BoneDustVar2((char) 165),
    BonesInFloorVar2((char) 166),
    BonesInFloorVar3((char) 167),
    Flowers((char) 168),
    FullBlockVar1((char) 169),
    FullBlockVar2((char) 170),
    FullBlockVar3((char) 171),
    WoodFloorVar1((char) 172),
    WoodFloorVar2((char) 173),
    DoorVar1((char) 224),
    DoorVar2((char) 225),
    DoorVar3((char) 226),
    DoorVar4((char) 227),
    FloorVar3((char) 229),
    FloorVar4((char) 230),
    FloorVar5((char) 231),
    FloorVar6((char) 232),
    FloorVar7((char) 233),
    FloorVar8((char) 234),
    FloorVar9((char) 235),
    CameVar1((char) 238),
    CameVar2((char) 239),
    GrassVar1((char) 245),
    GrassVar2((char) 246),
    GrassVar3((char) 247),
    GrassVar4((char) 248),
    GrassVar5((char) 249),
    GrassVar6((char) 250),
    CementFloorVar1((char) 251),
    CementFloorVar2((char) 252),
    CementFloorVar3((char) 253),
    CementFloorVar4((char) 254);

    private final char tileChar;

    TileType(char tileChar) {
        this.tileChar = tileChar;
    }

    public char getTileChar() {
        return tileChar;
    }

    public static boolean isPassable(char tileChar) {
        for (TileType tile : TileType.values()) {
            if (tile.getTileChar() == tileChar) {
                return true;
            }
        }
        return false;
    }
}
